app:
  port: 8080

log:
  error_path: log/error
  info_path: log/info
  max_age: 168
  rotation: 1

mysql:
  master:
    host: 127.0.0.1
    port: 3307
    user: root
    password: 123456
    db: mbit
  slave:
      - host: 127.0.0.1
        port: 3308
        user: root
        password: 123456
        db: mbit
      - host: 127.0.0.1
        port: 3308
        user: root
        password: 123456
        db: mbit
  base:
    data: 1
    max_open_conn: 100
    max_idle_conn: 60
    conn_max_life_time: 60

email:
  host: smtp.163.com
  port: 25
  username: mbitchina@163.com
  password: TWMKFVLDTHSDUVZC

redis:
  addr:
    - "192.168.51.3:7001"
    - "192.168.51.3:7002"
    - "192.168.51.3:7003"
    - "192.168.51.3:7004"
    - "192.168.51.3:7005"
    - "192.168.51.3:7006"
  db: 0
  max_retries: 3
  min_idle_conns: 5
  pass: ""
  pool_size: 10

rabbitmq:
  host: "127.0.0.1"
  port: 5672
  username: guest
  password: guest
  max_open: 10
  max_idle: 5
  max_attempts: 5
  exchanges:
    user: "user_exchange"
  queues:
    send_email: "send_email_queue"
  routing_key:
    public: "#"
