app:
  port: 8001
  name: uc

log:
  error_path: log/error
  info_path: log/info
  max_age: 168
  rotation: 1

mysql:
  master:
    host: 127.0.0.1
    port: 3307
    user: root
    password: 123456
    db: mbit
  slave:
      - host: 127.0.0.1
        port: 3308
        user: root
        password: 123456
        db: mbit
      - host: 127.0.0.1
        port: 3308
        user: root
        password: 123456
        db: mbit
  base:
    data: 1
    max_open_conn: 100
    max_idle_conn: 60
    conn_max_life_time: 60

email:
  host: smtp.163.com
  port: 25
  username: mbitchina@163.com
  password: TWMKFVLDTHSDUVZC

redis:
  addr:
    - "127.0.0.1:6379"
  db: 0
  max_retries: 3
  min_idle_conns: 5
  pass: ""
  pool_size: 10

rabbitmq:
  host: "127.0.0.1"
  port: 5672
  username: guest
  password: guest
  max_open: 10
  max_idle: 5
  exchanges:
    user: "user_exchange"
  queues:
    send_email: "send_email_queue"
  routing_key:
    public: "#"
jwt:
  access_token_expired_time: 2
  refresh_token_expired_time: 720
  secret: "0KV8xHl6uLeVzQtCZQ0FTpaRO1oTBYRKx9bHzv5ABHKWw3jZExQ9YtnS2OA1VEa1Vo87a3kUyYbcMYQN2cPBWBOiA3DglOgUycPz83EEDf1kjm5RCtF9fdNwKG3c8VKg7gC0DvJgh6XfOjWflCzfWB1vZb8ozPcoYejUBA7DHMMGiHMzLHDlaIhNCznCEzRssIU92YhIf0bTJnST78v0JfayPM0XNiGKekfQYX03yggE77Ky1AgrGpa61qCHiDiI"
